name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI (linting and tests)
    steps:
      - uses: actions/checkout@v2

      - name: Get node version
        id: nvm
        run: echo ::set-output name=version::$(cat .nvmrc | sed 's/v//')

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.version }}
          registry-url: https://npm.pkg.github.com
          scope: '@project'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Lint
        run: npm run lint

      - name: Test
        run: |
          mysql --user=root -h localhost --port=3307 --protocol="TCP" < ${{ github.workspace }}/.docker/mysql/project.sql
          npm run test:ci
        env: 
          NODE_ENV: test

    services:
      mysql:
        image: mysql:8.0.17
        ports:
          - 3307:3306
        env:
          MYSQL_DATABASE: project-tests
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
